# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pac1REoUAerDSP_N1hXoLhxhZ_s265-y
"""

import statistics as st

a= [10, 20, 50, 10, 21, 90]



mn = st.mean(a)
print("mean : ", mn)

md = st.mode(a)
print("mode :", md)

mdn = st.median(a)
print("median :", mdn)

import numpy as np

b =  np.array([[10, 20, 30, 50, 10],[1, 2, 3, 5, 6]])

print(b)

print(b.ndim)

b=np.array([[10, 20, 30, 50, 10],[1, 2, 3, 5, 6],[1,1,1,1,1]])
print(b)
print("Dim:",b.ndim)
print("Shape:",b.shape)

print("Size:",b.size)
print("Item Size:",b.itemsize)
print("Data type:",b.dtype)

c=np.empty((5,5))

d=np.arange(0,100,2)
print(d)

e=np.reshape(d,(10,5))
print(e)

f=np.reshape(e,(2,5,5))
 print(f)

g = np.full((3,3),5)
print(g)

print("Particular element:",d[10])

print("ELement upto 10:",d[:10])

print("Last 5 element:",d[-10:])

print("Alternative Numbers:",d[::2])

import pandas as pd

p_dict = {'pid':[1,2,3,4,5], 'value': [10,20,30,40,50], 'vendor':['V1','V2','V3','V4','V5']}

print(p_dict)

df = pd.DataFrame(p_dict)
df